# Number of days of inactivity before an issue becomes stale
daysUntilStale: 50
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 10
# Issues with these labels will never be considered stale
exemptLabels:
  - bug
  - pinned
  - documentation
  - enhancement
  - good first issue
  - help wanted
  - mirror request
  - question
# Label to use when marking an issue as stale
staleLabel: old and stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  If this issue is no longer to use,it will be closed in 10 days.
  Thanks for your contribution.(bot)
  (if anyone reply will unmark as stale)
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Your issue has been archived because it's 60 days no longer to use.
  Thanks for your contribution.(bot)
  Note:you can reopen this issue.
